# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-26 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorysub',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='categorysub1',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='categorysub2',
            name='cs1id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='property',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='propertyvalue',
            name='ptid',
        ),
        migrations.RemoveField(
            model_name='review',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='review',
            name='uid',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Categorysub',
        ),
        migrations.DeleteModel(
            name='CategorySub1',
        ),
        migrations.DeleteModel(
            name='CategorySub2',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Orderitem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Productimage',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='Propertyvalue',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
