# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-26 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180426_1852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='BannerImg',
        ),
        migrations.AlterModelTable(
            name='bannerimg',
            table='bannerimg',
        ),
    ]
